### ISSUE TITLE
check the throuput to the Chromecast and display a message

### ISSUE THREAD

**Issue by k3ck3c** [keredson/gnomecast#103]
I usually launch 

sudo nethogs

while using gnomecast, in order to check the process sends with a minimal throuput from the server to the Chromecast.

Sometimes, due to a bad network or wifi issues, the throuput is too low and it fails.

Maybe we could send a message stating the throuput was too low, can't process the video

I do not know the minimal, but for example, when it works fine, I see in nethogs a minimal throuput of 220 kb/s

Maybe we could monitor this inside gnomecast and display a message, such as "the average throuput for the last 30 seconds was xxx, which is too low"?

Just some ideas

**Comment by keredson** [comment]
i've seen too low throughput only once, when i was streaming 2160p 10bit TrueHD off a shared drive.  (reading and casting over wifi =D)

when this happens it's pretty obvious because the video buffers.  so not sure presenting a notice to the user is going to be much benefit.  nor sure how i would calculate the correct value, as it's going to be specific on the file (and could change mid file, etc.)
