### ISSUE TITLE
Converting more than once

### ISSUE THREAD

**Issue by naugtur** [keredson/gnomecast#47]
I started playback and then stopped, searched network again and started playback again. gnomecast converted my file for the second time. Would be nice to avoid that by storing a temp file with the converted content.

Oh, and thanks for the great work, it's the most convenient chromecast app I've used.

**Comment by keredson** [comment]
It does actually.  If you go from one compatible device to another it will
reuse the existing file.  But because you refreshed the network you temp
had none selected, hence why the temp file got cleaned up.  Tho probably we
could make that a bit smarter.

I just ordered a Chromecast ultra to add 4k support.  Will try to think
about this as I'm doing that.

**Comment by koyadovic** [comment]
Storing it with it's md5sum as the filename could worth.

**Comment by keredson** [comment]
there's now a "save" button once transcoding is done to permanently save the transcoded version of the file (replacing the original).  this combined w/ gnomecast reusing transcoded files between devices of similar capabilities (just not across full refreshes of devices) i think adequately covers the need here w/o risking disk usage leaks.
