### ISSUE TITLE
use /var/tmp

### ISSUE THREAD

**Issue by kparal** [keredson/gnomecast#63]
`/tmp` is on many distributions a tmpfs device, only useful for storing small temporary files. Large temporary files (like a transcoded video) should not go there, but instead go to `/var/tmp`. Please use `/var/tmp` by default; or if you insist on `/tmp`, please detect whether `/tmp` is a standard dir or a tmpfs dir and adjust the behavior dynamically.

Thanks!

gnomecast 1.4.1
Fedora 28

**Comment by slumbergod** [comment]
For a day I was unable to log into my machine using lightdm gui interface. In the days leading up to it I had weird behaviour with apt saying there was no space left in root.

Turns out that gnomecast had completely filled up var/tmp without cleaning out transcoded mp4s afterwards. Is there a way to force it use /tmp instead?

**Comment by kparal** [comment]
@slumbergod You should file a separate ticket.
