### ISSUE TITLE
setup.py and MANIFEST.in still reference cast.png

### ISSUE THREAD

**Issue by fiendish** [keredson/gnomecast#9]
deleting cast.png broke the pip install "error: can't copy 'cast.png': doesn't exist or not a regular file" because it's still referenced.

Consider still including the logo as a file. It's useful to have one for making a .desktop file to add a Gnome shell launcher.

**Comment by keredson** [comment]
this should be fixed in the latest.  run `pip3 install --update gnomecast --no-cache-dir`. to pick it up if you're still getting the old version.

i would LOVE to not embed that stupid svg, but i can't get setuptools to include it.  here's my WIP if you have suggestions: https://github.com/keredson/gnomecast/pull/10

**Comment by keredson** [comment]
done
